buildscript {
    dependencies {
        classpath(libs.realm.gradle.plugin)
    }
}
plugins {
    alias libs.plugins.android.application apply false
    alias libs.plugins.android.library apply false
    alias libs.plugins.kotlin.android apply false
    alias libs.plugins.kotlin.jvm apply false
    alias libs.plugins.kapt apply false
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
