pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://dl.bintray.com/patrickfav/maven/' }
        maven { url "https://jitpack.io" }
        maven {
            url "https://github.com/wada811/Android-Material-Design-Colors/raw/master/repository/"
        }
    }
}

include ':app'
