[versions]
adapterdelegates3 = "3.1.0"
android-plugin = "9.1.1"
android-simple-tooltip = "0.2.0"
appcompat = "1.7.1"
androidx-activity = "1.13.0"
androidx-fragment = "1.8.9"
androidx-lifecycle = "2.10.0"
atv = "1.2.9"
cardview = "1.0.0"
cicerone = "7.1"
circleimageview = "3.1.0"
circularprogressview = "2.5.0"
constraintlayout = "2.2.1"
easinginterpolator = "v1.3.2"
material = "1.13.0"
minitemplator-repackaged = "1.4.1"
appmetrica = "8.1.0"
moxy = "2.2.2"
okhttp = "5.3.2"
pagerbullet = "1.2.0"
palette-ktx = "1.0.0"
permissionsdispatcher = "4.9.2"
photoview = "2.3.0"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
roundedimageview = "2.3.0"
sectioned-recyclerview = "0.5.0"
spectrum = "0.7.1"
tagsoup = "1.2.1"
universal-image-loader = "1.9.5"
viewbindingpropertydelegate = "1.5.9"
kotlin-coroutines = "1.11.0"
work-runtime-ktx = "2.11.2"
ksp-plugin = "2.3.5"
androidx-room = "2.8.4"


[libraries]
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
adapterdelegates3 = { module = "com.hannesdorfmann:adapterdelegates3", version.ref = "adapterdelegates3" }
android-simple-tooltip = { module = "com.github.douglasjunior:android-simple-tooltip", version.ref = "android-simple-tooltip" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
atv = { module = "com.github.bmelnychuk:atv", version.ref = "atv" }
cicerone = { module = "com.github.terrakok:cicerone", version.ref = "cicerone" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
circularprogressview = { module = "com.github.rahatarmanahmed:circularprogressview", version.ref = "circularprogressview" }
easinginterpolator = { module = "com.github.MasayukiSuda:EasingInterpolator", version.ref = "easinginterpolator" }
material = { module = "com.google.android.material:material", version.ref = "material" }
minitemplator-repackaged = { module = "org.bsc.util:minitemplator-repackaged", version.ref = "minitemplator-repackaged" }
appmetrica = { module = "io.appmetrica.analytics:analytics", version.ref = "appmetrica" }
moxy = { module = "com.github.moxy-community:moxy", version.ref = "moxy" }
moxy-androidx = { module = "com.github.moxy-community:moxy-androidx", version.ref = "moxy" }
moxy-compiler = { module = "com.github.moxy-community:moxy-compiler", version.ref = "moxy" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection" }
okhttp-coroutines = { module = "com.squareup.okhttp3:okhttp-coroutines" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }
pagerbullet = { module = "com.github.robohorse:PagerBullet", version.ref = "pagerbullet" }
permissionsdispatcher = { module = "com.github.permissions-dispatcher:permissionsdispatcher", version.ref = "permissionsdispatcher" }
permissionsdispatcher-processor = { module = "com.github.permissions-dispatcher:permissionsdispatcher-processor", version.ref = "permissionsdispatcher" }
photoview = { module = "com.github.chrisbanes:PhotoView", version.ref = "photoview" }
roundedimageview = { module = "com.makeramen:roundedimageview", version.ref = "roundedimageview" }
sectioned-recyclerview = { module = "com.afollestad:sectioned-recyclerview", version.ref = "sectioned-recyclerview" }
spectrum = { module = "com.thebluealliance:spectrum", version.ref = "spectrum" }
tagsoup = { module = "org.ccil.cowan.tagsoup:tagsoup", version.ref = "tagsoup" }
universal-image-loader = { module = "com.nostra13.universalimageloader:universal-image-loader", version.ref = "universal-image-loader" }
viewbindingpropertydelegate = { module = "com.github.kirich1409:viewbindingpropertydelegate", version.ref = "viewbindingpropertydelegate" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kapt = { id = "com.android.legacy-kapt", version.ref = "android-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin" }
