import java.text.DateFormat
import java.text.SimpleDateFormat

plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android
    alias libs.plugins.kapt
    alias libs.plugins.realm
}

static def getDateTime() {
    DateFormat df = new SimpleDateFormat("dd MMMMM yyyy")
    return df.format(new Date()) + " г."
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    def fileNaming = "ForPDA"

    def versionNumber = 223

    def versionMajor = "1"
    def versionMinor = "0"
    def versionPatch = "0"

    def versionBuild = -1
    def versionPropsFile = file('version.properties')
    compileSdk 34
    if (versionPropsFile.canRead()) {
        Properties versionProps = new Properties()
        versionProps.load(new FileInputStream(versionPropsFile))
        versionBuild = versionProps['VERSION_BUILD'].toInteger() + 1
        versionProps['VERSION_BUILD'] = versionBuild.toString()
        versionProps['DATE_BUILD'] = getDateTime()
        versionProps.store(versionPropsFile.newWriter(), null)
    }


    defaultConfig {
        applicationId "ru.forpdateam.forpda"
        versionCode versionNumber
        versionName "${versionMajor}.${versionMinor}.${versionPatch} (${versionBuild})"
        minSdkVersion 21
        targetSdkVersion 29
        vectorDrawables.useSupportLibrary = true
        buildConfigField "String", 'BUILD_DATE', '"' + getDateTime() + '"'
        ndk {
            abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
        }
    }

    signingConfigs {
        debug {
            storeFile rootProject.file(keystoreProperties['DEBUG_STORE_FILE'])
            storePassword keystoreProperties['DEBUG_STORE_PASSWORD']
            keyAlias keystoreProperties['DEBUG_KEY_ALIAS']
            keyPassword keystoreProperties['DEBUG_KEY_PASSWORD']
        }
        release {
            storeFile rootProject.file(keystoreProperties['DEBUG_STORE_FILE'])
            storePassword keystoreProperties['DEBUG_STORE_PASSWORD']
            keyAlias keystoreProperties['DEBUG_KEY_ALIAS']
            keyPassword keystoreProperties['DEBUG_KEY_PASSWORD']
        }
    }

    buildTypes {
        /*debug {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }*/
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions = ["type"]
    productFlavors {
        stable {
            dimension "type"
        }
        beta {
            applicationId 'ru.forpdateam.forpda.beta'
            versionCode versionNumber
            versionName "${versionMajor}.${versionMinor}.${versionPatch} (${versionBuild}) beta"
            dimension "type"
        }

        dev {
            applicationId 'ru.forpdateam.forpda.debug'
            versionCode versionNumber
            versionName "${versionMajor}.${versionMinor}.${versionPatch} (${versionBuild}) dev"
            dimension "type"
        }
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "${fileNaming}-${versionMajor}.${versionMinor}.${versionPatch}.apk"
        }
    }

    /*compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 // Changed to 17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17' // Changed to 17
    }*/
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES.txt', 'META-INF/LICENSE.txt', 'META-INF/NOTICE.txt', 'META-INF/NOTICE', 'META-INF/LICENSE', 'META-INF/DEPENDENCIES', 'META-INF/notice.txt', 'META-INF/license.txt', 'META-INF/dependencies.txt']
            pickFirsts += ['META-INF/rxjava.properties']
        }
    }
    splits {
        abi {
            enable gradle.startParameter.taskNames.contains(":app:assembleRelease")
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
            universalApk false
        }
    }
    namespace 'forpdateam.ru.forpda'
    buildFeatures {
        viewBinding true
        buildConfig true
    }
}
kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation libs.kotlin.coroutines.core
    implementation libs.kotlin.coroutines.rx2


    implementation(libs.androidx.activity)
    implementation(libs.androidx.fragment)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.livedata.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)

    implementation libs.androidx.constraintlayout
    implementation libs.androidx.palette.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.cardview
    implementation libs.androidx.recyclerview
    implementation libs.androidx.preference.ktx

    implementation platform(libs.okhttp.bom)
    implementation libs.okhttp
    implementation libs.okhttp.coroutines
    implementation libs.okhttp.urlconnection
    implementation libs.okhttp.logging.interceptor
    //implementation 'com.annimon:stream:1.1.4'
    implementation libs.rxandroid
    implementation libs.rxjava
    implementation libs.universal.image.loader
    implementation libs.circularprogressview
    implementation libs.circleimageview
    implementation libs.tagsoup
    implementation libs.minitemplator.repackaged
    //implementation 'com.lapism:searchview:4.0'
    implementation libs.atv
    implementation libs.sectioned.recyclerview

    implementation libs.photoview
    implementation libs.android.material.design.colors
    implementation libs.spectrum
    implementation libs.android.simple.tooltip
    implementation libs.pagerbullet
    implementation libs.android.job

    implementation libs.moxy
    implementation libs.moxy.androidx
    kapt libs.moxy.compiler

    implementation libs.rxrelay
    implementation libs.kotlin.stdlib

    implementation libs.cicerone
    implementation libs.adapterdelegates3
    implementation libs.easinginterpolator
    implementation libs.rx.preferences

    implementation libs.realm.base

    implementation(libs.permissionsdispatcher)
    kapt libs.permissionsdispatcher.processor

    implementation libs.mobmetricalib

    implementation libs.roundedimageview
    implementation libs.viewbindingpropertydelegate
}